spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ownerms
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
mail:
  service:
    url: http://localhost:9092/api/v1/mails
pet:
  service:
    base:
      url: http://localhost:9091/api/v1/pets
server:
  port: 9090