spring:
  application:
    name: mail-service
  config:
    import: configserver:http://localhost:8888
#  mail:
#    host: localhost
#    port: 1025
#    properties:
#      mail:
#        smtp:
#          auth: false
#          starttls:
#            enable: false
#    username: ${SYSTEM_EMAIL_ID}
#    password: ${SYSTEM_EMAIL_PASSWORD}
#server:
#  port: 9092
