spring:
  application:
    name: MailMS
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    username: ${SYSTEM_EMAIL_ID}
    password: ${SYSTEM_EMAIL_PASSWORD}
server:
  port: 9092
